# Generated by Django 5.0.3 on 2024-03-15 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_shift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='added', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_shift.workshift')),
            ],
        ),
        migrations.AddField(
            model_name='workshift',
            name='users',
            field=models.ManyToManyField(through='work_shift.ShiftUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
