# Generated by Django 5.0.3 on 2024-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_roles_remove_user_role_id_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
